name = "13th MEF";
author = "13th MEF Mod Team";
picture         = "logo.paa";           // Picture displayed from the expansions menu. Optimal size is 2048x1024
logo            = "logo.paa";        // Logo displayed in the main menu 128x128
logoOver        = "logo.paa";
logoSmall       = "logo.paa";
tooltip         = "13th MEF";
overview        = "*sob*";         // Overview text, displayed from the extension menu
description     = "13th MEF Mod"; // Probably in context with action
action          = "https://discord.gg/VEzJHZDwvQ";    // Website URL, that can accessed from the expansions menu 
//actionName      = "Website?";                 // label of button/tooltip in extension menu