name = "13th MEF"
prefix = "13thMEF"
author = "13th MOD TEAM"

[files]
include = [
    "mod.cpp",
    "logo.paa",
    "README.md",
    "LICENSE",
    "*.pbo"
]

exclude = [
    "*.png", # explicitly excluding image source files from build, but not repository
]

[version]
major = 6
minor = 0
patch = 0
build = 0
git_hash = 0